#ifndef SABATO_DEFINITIONS_HPP
#define SABATO_DEFINITIONS_HPP

#define SENSOR1_TEST_SIZE 100000
#define SENSOR2_AND_3_TEST_SIZE 3
#define SENSOR4_SIZE 1

#define CONTROLLER1_EVENT_TYPE "controller1_event"
#define CONTROLLER1_LOGGER "test_log"

#endif	// SABATO_DEFINITIONS_HPP
